# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'DoneFast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
# Pods for DoneFast

  use_frameworks!

	pod 'Alamofire', '~> 4.4'
	pod 'SwiftyJSON', '~> 4.0'
	pod 'GoogleMaps'
	pod 'GooglePlaces'

  target 'DoneFastTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
